### ISSUE TITLE
Does this support the "MIT Elite Plus" model?

### ISSUE THREAD

**Issue by Magnum5234** [LazyT/obpm#19]
I'm currently evaluating buying a blood pressure monitor. And hearing words like cloud and app are leading to the the rise of said blood pressure. That's why I was wondering what model to buy.

I did not find much information on this model. But here is the manual:
https://www.omron-healthcare.com/de/support/manuals/search?utf8=%E2%9C%93&q=HEM-7301&commit=search

Thank you in advance for your great work here!

**Comment by azyata** [comment]
Firstly I want to say your work and possibilities you have opened up are stunning!

I also would love to see support for MIT Elite Plus. I bought it due to great reviews and didn't check that I would have so many problems with connecting it on Linux. 

![image](https://user-images.githubusercontent.com/37910941/47942734-550af200-def3-11e8-8f44-f85d5fba3f5a.png)


Your program is awesome and adding support for this device should help automate mine and other people's routine. And allow MIT Elite Plus owners to visualize our BP trends.
I think I could lend you my device, so you could implement nessessary code, if you find that interesting. 

I would like to make it happen, because I'm planning to send BP data to Grafana using Raspberry Pi and your program is the best bet to make it happen.

**Comment by LazyT** [comment]
You could try changing the usb device ids for this device located in usb.h line 8+9

`#define VID 0x0590	// Omron
#define PID 0x0090	// M400IT & M500IT`

Then compile and try again if it is detected now. But I don't know if this devices uses the same protocol and will be compatible...

**Comment by azyata** [comment]
Thanks for the answer. I've changed it as you said but now I have this problem :disappointed: 
>Could not open selected device!

Both - M3 and M6 - are not working.
![screenshot from 2018-11-03 16-07-30](https://user-images.githubusercontent.com/37910941/47953902-a2cf3b00-df83-11e8-99c5-3ddc0de746ad.png)

**Comment by azyata** [comment]
When I ran program with `sudo` something happened.

![image](https://user-images.githubusercontent.com/37910941/47954161-5554cd00-df87-11e8-824b-99f0e309f720.png)


You gave me cli version and when I ran it I received

```
azjata@HARDING:~/obpm-cli$ sudo ./omron

>>> Omron M500IT cmdtool 1.0 by Thomas "LazyT" Löwe 2015 <<<

manufacturer    : OMRON Corporation
product         : HHX-CABLE-USB1
serial          : HHX-CABLE-USB1

-> -01 bytes: 02 08 00 00 00 00 10 00 18
<- 00 bytes: timeout! press start/stop on device and try again...
```

I tried with different combinations with start/stop button but without success...

**Comment by azyata** [comment]
I've changed 
`unsigned char payload[40*70];	// max 70 usb transfers a 40 byte, 1 data set = 14 bytes, user 2 starts @ 0x0824`

To 

`unsigned char payload[40*90];	// max 90 usb transfers a 40 byte, 1 data set = 14 bytes, user 2 starts @ 0x0824`

Because this device have memory of 90 measurements. But without success... :disappointed: 

Protocol must be different.

**Comment by azyata** [comment]
I have installed Omron software on my gf's laptop and dump data from my device. And sniffed communications between them two. There is a lot of HEX stuff going on. These files should help someone implement protocol. 

[MITElitePlus_payload.txt](https://github.com/LazyT/obpm/files/2545164/MITElitePlus_payload.txt)
[MITElitePlus_rawdata.txt](https://github.com/LazyT/obpm/files/2545165/MITElitePlus_rawdata.txt)

**Comment by azyata** [comment]
Just realized that someone will need clear entries to compare it to raw data and payload.

[azjata BP Report 110418.pdf](https://github.com/LazyT/obpm/files/2545418/azjata.BP.Report.110418.pdf)

[azjata BP Report 110418.txt - change extension to csv if not working](https://github.com/LazyT/obpm/files/2545419/azjata.BP.Report.110418.txt)

**Comment by LazyT** [comment]
This is theoretically possible now with the successor [UBPM](https://codeberg.org/LazyT/ubpm).

But someone has to code a device plugin first.

if you still own the device we could try together. Please contact me via E-Mail.
