### ISSUE TITLE
OBPM AppImage

### ISSUE THREAD

**Issue by probonopd** [LazyT/obpm#5]
I thought you might be interested in my [AppImage](http://appimage.org/) for Linux. Just download, `chmod a+x OBPM-*.AppImage`, and run. 

Using AppImage, application authors can provide packages for Linux desktop systems, without the need to get it 'into' a distribution and without having to build for gazillions of different distributions.

OBPM AppImage
[![Download](https://api.bintray.com/packages/probono/AppImages/OBPM/images/download.svg)](https://bintray.com/probono/AppImages/OBPM/_latestVersion#files)

The build script that is used to generate this lives [here](https://github.com/probonopd/AppImages/blob/master/recipes/obpm/Recipe).

Of course you are free to integrate it into your "official" build chain.

**Comment by LazyT** [comment]
Hi Simon,

sorry for the late response.

Looks interesting, but 2 things:

- the German translation/help is missing
- because install/update is not required/possible you can remove the following files (Licenses, InstallationLog.txt, components.xml, maintenancetool*, network.xml)

As I understand it's an iso with exe-header which mounts the iso and run the app without installing. This will break the new feature of online updates (user don't have to download, uninstall old, install new - it updates now automatically only the changed parts).

What I don't understand: when you include the binary/libs from my installer how can this be run on "any" distribution? When this works the installer should work too?

**Comment by probonopd** [comment]
Yes, the Qt installer also is mostly distribution-independent, so you are already having this advantage. But users still have to run an installer which is no longer needed with AppImage. Also, there is a very efficient delta update mechanism in the works where updates can be downloaded by just downloading a binary diff.

Thanks for your hint to remove the extra files. (Don't know where I lost the German help though...)
